export const ListData = [
  {
    title: "Waffle",
    subTitle: "Waffle With Berries",
    price: "$6.50",
    selected: false,
    key: 0,
  },
  {
    title: "Creme Brulle",
    subTitle: "Vanilla Bean Creme Brulle",
    price: "$7.00",
    selected: false,
    key: 1,
  },
  {
    title: "Macaron",
    subTitle: "Macaron Mix Of Five",
    price: "$8.00",
    selected: false,
    key: 2,
  },
  {
    title: "Tiramisu",
    subTitle: "Classic Tiramisu",
    price: "$5.50",
    selected: false,
    key: 3,
  },
  {
    title: "Baklava",
    subTitle: "Pistachio Baklava",
    price: "$4.00",
    selected: false,
    key: 4,
  },
  {
    title: "Pie",
    subTitle: "Lemon Pie Meringue",
    price: "$7.00",
    selected: false,
    key: 5,
  },
  {
    title: "Cake",
    subTitle: "Red Velvet Cake",
    price: "$4.50",
    selected: false,
    key: 6,
  },
  {
    title: "Brownie",
    subTitle: "Salted Caramel Brownie",
    price: "$5.50",
    selected: false,
    key: 7,
  },
  {
    title: "Panna Cotta",
    subTitle: "Vanilla Panna Cotta",
    price: "$6.50",
    selected: false,
    key: 8,
  },
];
